name: Dine And Fly
favicon: null
layout_spectrum: 0.6239254160318524
typography_spectrum: 0.00005961628630757332
title: 'Discover unique holiday offers in Malta, Tenerife and Spain'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.010447483975440264
  lightness: 0.7155410640407354
  saturation: 0.889818005496636
  rhythmicContrast: 0.8124664577189833
purpose: []
