typography_spectrum: 0.592342
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.715541
  saturation: 0.889818
  rhythmicContrast: 0.812466
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Dine And Fly
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ready To Fly
purpose: []
