analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.715541
  rhythmicContrast: 0.812466
  saturation: 0.889818
cta: {}
layout_spectrum: 0
name: Dine And Fly
opengraph: {}
purpose: []
typography_spectrum: 0.592342
